[package]
name = "mobi"
version = "0.0.1"
authors = ["Max Böcker <max.boecker@rwth-aachen.de>"]
edition = "2018"

[dependencies]
mobi-sys = { git = "https://github.com/morbatex/mobi-sys" }
libc = "0.2.43"
